"""
Core classes for the UniInfer package.
"""
from typing import List, Dict, Any, Iterator, Optional, Union


class ChatMessage:
    """
    A message in a chat conversation.

    Attributes:
        role (str): The role of the message sender (user, assistant, system).
        content (str): The content of the message.
        tool_calls (Optional[List[Dict]]): Tool calls generated by the model.
        tool_call_id (Optional[str]): ID of the tool call this message responds to.
    """

    def __init__(self, role: str, content: Union[str, List[Dict], None], tool_calls: Optional[List[Dict]] = None, tool_call_id: Optional[str] = None):
        self.role = role
        self.content = content
        self.tool_calls = tool_calls
        self.tool_call_id = tool_call_id

    def to_dict(self) -> Dict[str, Any]:
        """Convert to a dictionary format suitable for API requests."""
        data = {
            "role": self.role,
            "content": self.content
        }
        if self.tool_calls:
            data["tool_calls"] = self.tool_calls
        if self.tool_call_id:
            data["tool_call_id"] = self.tool_call_id
        return data


class ChatCompletionRequest:
    """
    A request for a chat completion.

    Attributes:
        messages (List[ChatMessage]): The conversation history.
        model (Optional[str]): The model to use for completion.
        temperature (float): Controls randomness in generation.
        max_tokens (Optional[int]): Maximum tokens to generate.
        streaming (bool): Whether to stream the response.
        tools (Optional[List[Dict]]): List of tools available to the model.
        tool_choice (Optional[Any]): Tool choice preference.
    """

    def __init__(
        self,
        messages: List[ChatMessage],
        model: Optional[str] = None,
        temperature: float = 1.0,
        max_tokens: Optional[int] = None,
        streaming: bool = False,
        tools: Optional[List[Dict]] = None,
        tool_choice: Optional[Any] = None
    ):
        self.messages = messages
        self.model = model
        self.temperature = temperature
        self.max_tokens = max_tokens
        self.streaming = streaming
        self.tools = tools
        self.tool_choice = tool_choice


class ChatCompletionResponse:
    """
    A response from a chat completion.

    Attributes:
        message (ChatMessage): The generated message.
        provider (str): The provider that generated the response.
        model (str): The model used for generation.
        usage (Dict): Token usage information.
        raw_response (Any): The raw response from the provider.
    """

    def __init__(
        self,
        message: ChatMessage,
        provider: str,
        model: str,
        usage: Dict,
        raw_response: Any,
        finish_reason: Optional[str] = None
    ):
        self.message = message
        self.provider = provider
        self.model = model
        self.usage = usage
        self.raw_response = raw_response
        self.finish_reason = finish_reason


class ChatProvider:
    """
    Abstract base class for chat providers.

    All provider implementations must inherit from this class and implement
    the complete and stream_complete methods.
    """

    def __init__(self, api_key: Optional[str] = None, **kwargs):
        """
        Initialize the provider with an API key and optional configuration.

        Args:
            api_key (Optional[str]): The API key for authentication.
            **kwargs: Additional provider-specific configuration parameters.
        """
        self.api_key = api_key
        # Additional provider-specific configuration can be handled by subclasses

    @classmethod
    def list_models(cls, api_key: Optional[str] = None, **kwargs) -> List[str]:
        """
        Standard interface for listing available models.

        Args:
            api_key (Optional[str]): API key if needed for listing models
            **kwargs: Additional provider-specific parameters

        Returns:
            List[str]: List of available model names
        """
        raise NotImplementedError("Providers must implement list_models")

    def complete(
        self,
        request: ChatCompletionRequest,
        **provider_specific_kwargs
    ) -> ChatCompletionResponse:
        """
        Make a chat completion request.

        Args:
            request (ChatCompletionRequest): The request to make.
            **provider_specific_kwargs: Additional provider-specific parameters.

        Returns:
            ChatCompletionResponse: The completion response.
        """
        raise NotImplementedError(
            "Providers must implement the complete method")

    def stream_complete(
        self,
        request: ChatCompletionRequest,
        **provider_specific_kwargs
    ) -> Iterator[ChatCompletionResponse]:
        """
        Stream a chat completion response.

        Args:
            request (ChatCompletionRequest): The request to make.
            **provider_specific_kwargs: Additional provider-specific parameters.

        Returns:
            Iterator[ChatCompletionResponse]: An iterator of response chunks.
        """
        raise NotImplementedError(
            "Providers must implement the stream_complete method")


class EmbeddingRequest:
    """
    A request for embeddings.

    Attributes:
        input (List[str]): The texts to embed.
        model (Optional[str]): The model to use for embedding.
        encoding_format (str): The format to return the embeddings in.
        dimensions (Optional[int]): The number of dimensions the resulting output embeddings should have.
        user (Optional[str]): A unique identifier representing your end-user.
    """

    def __init__(
        self,
        input: List[str],
        model: Optional[str] = None,
        encoding_format: str = "float",
        dimensions: Optional[int] = None,
        user: Optional[str] = None
    ):
        self.input = input
        self.model = model
        self.encoding_format = encoding_format
        self.dimensions = dimensions
        self.user = user


class EmbeddingResponse:
    """
    A response from an embedding request.

    Attributes:
        object (str): The object type, always "list".
        data (List[Dict]): The embedding data.
        model (str): The model used for embedding.
        usage (Dict): Token usage information.
        provider (str): The provider that generated the response.
        raw_response (Any): The raw response from the provider.
    """

    def __init__(
        self,
        object: str,
        data: List[Dict],
        model: str,
        usage: Dict,
        provider: str,
        raw_response: Any
    ):
        self.object = object
        self.data = data
        self.model = model
        self.usage = usage
        self.provider = provider
        self.raw_response = raw_response


class EmbeddingProvider:
    """
    Abstract base class for embedding providers.

    All embedding provider implementations must inherit from this class and implement
    the embed method.
    """

    def __init__(self, api_key: Optional[str] = None, **kwargs):
        """
        Initialize the provider with an API key and optional configuration.

        Args:
            api_key (Optional[str]): The API key for authentication.
            **kwargs: Additional provider-specific configuration parameters.
        """
        self.api_key = api_key
        # Additional provider-specific configuration can be handled by subclasses

    @classmethod
    def list_models(cls, **kwargs) -> List[str]:
        """
        Standard interface for listing available models.

        Args:
            **kwargs: Additional provider-specific parameters

        Returns:
            List[str]: List of available model names
        """
        raise NotImplementedError(
            "Embedding providers must implement list_models")

    def embed(
        self,
        request: EmbeddingRequest,
        **provider_specific_kwargs
    ) -> EmbeddingResponse:
        """
        Make an embedding request.

        Args:
            request (EmbeddingRequest): The request to make.
            **provider_specific_kwargs: Additional provider-specific parameters.

        Returns:
            EmbeddingResponse: The embedding response.
        """
        raise NotImplementedError(
            "Embedding providers must implement the embed method")


class TTSRequest:
    """
    A request for text-to-speech generation.

    Attributes:
        input (str): The text to convert to speech.
        model (Optional[str]): The model to use for TTS.
        voice (Optional[str]): The voice to use.
        response_format (str): The audio format (mp3, opus, aac, flac, wav, pcm).
        speed (float): The speed of the generated audio (0.25 to 4.0).
        instructions (Optional[str]): Additional instructions for the TTS model.
    """

    def __init__(
        self,
        input: str,
        model: Optional[str] = None,
        voice: Optional[str] = None,
        response_format: str = "mp3",
        speed: float = 1.0,
        instructions: Optional[str] = None
    ):
        self.input = input
        self.model = model
        self.voice = voice
        self.response_format = response_format
        self.speed = speed
        self.instructions = instructions


class TTSResponse:
    """
    A response from a TTS request.

    Attributes:
        audio_content (bytes): The generated audio content.
        model (str): The model used for generation.
        provider (str): The provider that generated the response.
        content_type (str): The MIME type of the audio content.
        raw_response (Any): The raw response from the provider.
    """

    def __init__(
        self,
        audio_content: bytes,
        model: str,
        provider: str,
        content_type: str = "audio/mpeg",
        raw_response: Any = None
    ):
        self.audio_content = audio_content
        self.model = model
        self.provider = provider
        self.content_type = content_type
        self.raw_response = raw_response


class TTSProvider:
    """
    Abstract base class for TTS providers.

    All TTS provider implementations must inherit from this class and implement
    the generate_speech method.
    """

    def __init__(self, api_key: Optional[str] = None, **kwargs):
        """
        Initialize the provider with an API key and optional configuration.

        Args:
            api_key (Optional[str]): The API key for authentication.
            **kwargs: Additional provider-specific configuration parameters.
        """
        self.api_key = api_key

    @classmethod
    def list_models(cls, api_key: Optional[str] = None, **kwargs) -> List[str]:
        """
        Standard interface for listing available TTS models.

        Args:
            api_key (Optional[str]): API key if needed for listing models
            **kwargs: Additional provider-specific parameters

        Returns:
            List[str]: List of available model names
        """
        raise NotImplementedError("TTS providers must implement list_models")

    def generate_speech(
        self,
        request: TTSRequest,
        **provider_specific_kwargs
    ) -> TTSResponse:
        """
        Generate speech from text.

        Args:
            request (TTSRequest): The request to make.
            **provider_specific_kwargs: Additional provider-specific parameters.

        Returns:
            TTSResponse: The TTS response with audio content.
        """
        raise NotImplementedError(
            "TTS providers must implement the generate_speech method")


class STTRequest:
    """
    A request for speech-to-text transcription.

    Attributes:
        file (Union[str, bytes]): The audio file path or content to transcribe.
        model (Optional[str]): The model to use for transcription.
        language (Optional[str]): The language of the audio (ISO-639-1 format).
        prompt (Optional[str]): Optional text to guide the model's style.
        response_format (str): The format of the transcript output.
        temperature (float): Sampling temperature (0 to 1).
        timestamp_granularities (Optional[List[str]]): Timestamp granularities.
    """

    def __init__(
        self,
        file: Union[str, bytes],
        model: Optional[str] = None,
        language: Optional[str] = None,
        prompt: Optional[str] = None,
        response_format: str = "json",
        temperature: float = 0.0,
        timestamp_granularities: Optional[List[str]] = None
    ):
        self.file = file
        self.model = model
        self.language = language
        self.prompt = prompt
        self.response_format = response_format
        self.temperature = temperature
        self.timestamp_granularities = timestamp_granularities


class STTResponse:
    """
    A response from an STT request.

    Attributes:
        text (str): The transcribed text.
        model (str): The model used for transcription.
        provider (str): The provider that generated the response.
        language (Optional[str]): Detected or specified language.
        duration (Optional[float]): Duration of the audio in seconds.
        segments (Optional[List[Dict]]): Detailed segments with timestamps.
        raw_response (Any): The raw response from the provider.
    """

    def __init__(
        self,
        text: str,
        model: str,
        provider: str,
        language: Optional[str] = None,
        duration: Optional[float] = None,
        segments: Optional[List[Dict]] = None,
        raw_response: Any = None
    ):
        self.text = text
        self.model = model
        self.provider = provider
        self.language = language
        self.duration = duration
        self.segments = segments
        self.raw_response = raw_response


class STTProvider:
    """
    Abstract base class for STT providers.

    All STT provider implementations must inherit from this class and implement
    the transcribe method.
    """

    def __init__(self, api_key: Optional[str] = None, **kwargs):
        """
        Initialize the provider with an API key and optional configuration.

        Args:
            api_key (Optional[str]): The API key for authentication.
            **kwargs: Additional provider-specific configuration parameters.
        """
        self.api_key = api_key

    @classmethod
    def list_models(cls, api_key: Optional[str] = None, **kwargs) -> List[str]:
        """
        Standard interface for listing available STT models.

        Args:
            api_key (Optional[str]): API key if needed for listing models
            **kwargs: Additional provider-specific parameters

        Returns:
            List[str]: List of available model names
        """
        raise NotImplementedError("STT providers must implement list_models")

    def transcribe(
        self,
        request: STTRequest,
        **provider_specific_kwargs
    ) -> STTResponse:
        """
        Transcribe audio to text.

        Args:
            request (STTRequest): The request to make.
            **provider_specific_kwargs: Additional provider-specific parameters.

        Returns:
            STTResponse: The STT response with transcribed text.
        """
        raise NotImplementedError(
            "STT providers must implement the transcribe method")
